name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: macos-15
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for gitversion
          submodules: true

      - run: |
          /bin/bash -c "sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer"

          echo "Listing iOS simulators"
          xcrun simctl list devices --json

          export UNO_UITEST_SIMULATOR_VERSION="com.apple.CoreSimulator.SimRuntime.iOS-18-1"
          export UNO_UITEST_SIMULATOR_NAME="iPad Pro 13-inch (M4)"

          export UITEST_IOSDEVICE_ID=`xcrun simctl list -j | jq -r --arg sim "$UNO_UITEST_SIMULATOR_VERSION" --arg name "$UNO_UITEST_SIMULATOR_NAME" '.devices[$sim] | .[] | select(.name==$name) | .udid'`
          xcrun simctl boot

          sleep 300
        name: Run
